services:
    upload-service:
        build:
            context: ./upload-service
            dockerfile: Dockerfile
        container_name: upload-service
        ports:
            - "8081:8081"
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
            OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    compression-worker:
        build:
            context: ./compression-worker
            dockerfile: Dockerfile
        container_name: compression-worker
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: docker
            OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

