apiVersion: 1

datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
      jsonData:
          httpMethod: GET
          exemplarTraceIdDestinations:
              - datasourceUid: tempo
                name: trace_id
    - name: Zipkin
      type: zipkin
      access: proxy
      orgId: 1
      url: http://zipkin:9411
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
      apiVersion: 1
      uid: zipkin
      jsonData:
          tracesToLogsV2:
              datasourceUid: loki
              spanStartTimeShift: '-1h'
              spanEndTimeShift: '1h'
              filterByTraceID: true
              filterBySpanID: true
              tags: [ { key: 'service', value: 'job' } ]