apiVersion: v1
kind: Secret
metadata:
    name: aws-secrets
    labels:
        app: compression-service
        environment: production
type: Opaque
data:
    access-key: <base64-encoded-access-key>
    secret-key: <base64-encoded-secret-key>