apiVersion: v1
kind: Service
metadata:
    name: compression-service
    labels:
        app: compression-service
        environment: production
spec:
    selector:
        app: compression-service
    ports:
        -   protocol: TCP
            port: 8081
            targetPort: 8081
    type: ClusterIP