apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
spec:
    replicas: 1
    selector:
        matchLabels:
            app: grafana
    template:
        metadata:
            labels:
                app: grafana
        spec:
            containers:
                - name: grafana
                  image: grafana/grafana
                  volumeMounts:
                      - name: grafana-datasources
                        mountPath: /etc/grafana/provisioning/datasources/datasources.yml
                        subPath: datasources.yml
                  ports:
                      - containerPort: 3000
            volumes:
                - name: grafana-datasources
                  configMap:
                      name: grafana-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: grafana-datasources
data:
    datasources.yml: |
        apiVersion: 1
        
        datasources:
            - name: Prometheus
              type: prometheus
              uid: prometheus
              access: proxy
              orgId: 1
              url: http://prometheus:9090
              basicAuth: false
              isDefault: false
              version: 1
              editable: false
              jsonData:
                  httpMethod: GET
                  exemplarTraceIdDestinations:
                      - datasourceUid: tempo
                        name: trace_id
            - name: Zipkin
              type: zipkin
              access: proxy
              orgId: 1
              url: http://zipkin:9411
              basicAuth: false
              isDefault: false
              version: 1
              editable: false
              apiVersion: 1
              uid: zipkin
              jsonData:
                  tracesToLogsV2:
                      datasourceUid: loki
                      spanStartTimeShift: '-1h'
                      spanEndTimeShift: '1h'
                      filterByTraceID: true
                      filterBySpanID: true
                      tags: [ { key: 'service', value: 'job' } ]
---
apiVersion: v1
kind: Service
metadata:
    name: grafana
spec:
    type: NodePort
    ports:
        - port: 3000
          targetPort: 3000
          nodePort: 32000  # You can specify a port between 30000 and 32767
    selector:
        app: grafana
