apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: upload-service-hpa
    labels:
        app: upload-service
        environment: production
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: upload-service
    minReplicas: 2
    maxReplicas: 4
    metrics:
        -   type: Resource
            resource:
                name: cpu
                target:
                    type: Utilization
                    averageUtilization: 70