apiVersion: v1
kind: Secret
metadata:
    name: aws-secrets
    labels:
        app: upload-service
        environment: production
type: Opaque
data:
    access-key: QUtJQVU2VlRuTVdBRVFWQlJGWFa=
    secret-key: ajdobkEvQjZNdHU1ZXRBMkNoZ3ZFQ013eDZWaWE1R2ljT1ptVGRLdw==