apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus
spec:
    replicas: 1
    selector:
        matchLabels:
            app: prometheus
    template:
        metadata:
            labels:
                app: prometheus
        spec:
            containers:
                - name: prometheus
                  image: prom/prometheus
                  args: ["--config.file=/etc/prometheus/prometheus.yml", "--enable-feature=exemplar-storage", "--web.enable-remote-write-receiver"]

                  volumeMounts:
                      - name: prometheus-config
                        mountPath: /etc/prometheus/prometheus.yml
                        subPath: prometheus.yml
                  ports:
                      - containerPort: 9090
            volumes:
                - name: prometheus-config
                  configMap:
                      name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-config
data:
    prometheus.yml: |
        global:
            scrape_interval: 15s
            scrape_timeout: 10s
            evaluation_interval: 15s
        
        scrape_configs:
            - job_name: otel_collector
              honor_timestamps: true
              scrape_interval: 15s
              scrape_timeout: 10s
              metrics_path: /metrics
              scheme: http
              static_configs:
                  - targets:
                        - collector:8889
---
apiVersion: v1
kind: Service
metadata:
    name: prometheus
spec:
    ports:
        - port: 9090
          targetPort: 9090
    selector:
        app: prometheus