image:
    debug: true

    tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"

externalAccess:
    enabled: true
    broker:
        service:
            type: LoadBalancer
            ports:
                external: 9094
    controller:
        service:
            type: LoadBalancer
            containerPorts:
                external: 9094
    autoDiscovery:
        enabled: true

defaultInitContainers:
    autoDiscovery:
        enabled: true

kraft:
    enabled: true
    replicas: 3
    zookeeper:
        enabled: false
extraEnvVars:
    - name: KAFKA_ENABLE_KRAFT
      value: "true"
    - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
      value: "true" # enable topic deletion
    - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
      value: "true" # enable auto topic creation

serviceAccount:
    create: true
rbac:
    create: true

controller:
    automountServiceAccountToken: true
broker:
    automountServiceAccountToken: true