apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.service.name }}-secrets
    labels:
        app: {{ .Values.service.name }}
        environment: production
type: Opaque
data:
    # Значення кодуються у base64
    access-key: {{ .Values.awsSecrets.accessKey}}
    secret-key: {{ .Values.awsSecrets.secretKey}}