server:
    port: 8081

spring:
    application:
        name: upload-service
    neo4j:
        uri: ${SPRING_NEO4J_URI:bolt://neo4j:7687}
        authentication:
            password: ${SPRING_NEO4J_PASSWORD:password}
            username: ${SPRING_NEO4J_USERNAME:neo4j}
    data:
        redis:
            url: ${SPRING_REDIS_URL:redis://redis:6379}
            host: ${SPRING_REDIS_HOST:redis}
            port: ${SPRING_REDIS_PORT:6379}
            password: ${SPRING_REDIS_PASSWORD:password}
            username: ${SPRING_REDIS_USERNAME:redis}
    kafka:
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
        topic:
            file-compression: ${SPRING_KAFKA_TOPIC_FILE_COMPRESSION:file-compression}
