server:
    port: 8080

spring:
    neo4j:
        uri: ${SPRING_NEO4J_URI:bolt://neo4j.default.svc.cluster.local:7687}
        authentication:
            password: ${SPRING_NEO4J_PASSWORD:password}
            username: ${SPRING_NEO4J_USERNAME:neo4j}
    data:
        redis:
            host: ${SPRING_REDIS_HOST:redis-master.default.svc.cluster.local}
            port: ${SPRING_REDIS_PORT:6379}
            password: ${SPRING_REDIS_PASSWORD:mysecretpassword}
    kafka:
        bootstrap-servers:
            - my-kafka-cluster-controller-0.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
            - my-kafka-cluster-controller-1.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
            - my-kafka-cluster-controller-2.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
        topic:
            file-compression: ${SPRING_KAFKA_TOPIC_FILE_COMPRESSION:file-compression}
        consumer:
            bootstrap-servers:
                - my-kafka-cluster-controller-0.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
                - my-kafka-cluster-controller-1.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
                - my-kafka-cluster-controller-2.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
        properties:
            sasl:
                jaas:
                    config: ${SPRING_KAFKA_SASL_JAAS_CONFIG:org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="password";}
                mechanism: ${SPRING_KAFKA_SASL_MECHANISM:PLAIN}
            security:
                protocol: ${SPRING_KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
        producer:
            bootstrap-servers:
                - my-kafka-cluster-controller-0.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
                - my-kafka-cluster-controller-1.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
                - my-kafka-cluster-controller-2.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
        streams:
            bootstrap-servers:
                - my-kafka-cluster-controller-0.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
                - my-kafka-cluster-controller-1.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092
                - my-kafka-cluster-controller-2.my-kafka-cluster-controller-headless.default.svc.cluster.local:9092