auth:
    enabled: true
    password: mysecretpassword

architecture: replication

master:
    persistence:
        enabled: true
        size: 8Gi

replica:
    replicaCount: 2
    persistence:
        enabled: true
        size: 8Gi